### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Monolog\Handler\StreamHandler' not found

### ISSUE THREAD

**Issue by PauloBoaventura** [puleeno/medoid#18]
Fatal error: Uncaught Error: Class 'Monolog\Handler\StreamHandler' not found in /home/clubnation.com.br/public_html/wp-content/plugins/medoid/includes/class-medoid.php:22 Stack trace: #0 /home/clubnation.com.br/public_html/wp-content/plugins/medoid/includes/class-medoid.php(11): Medoid->__construct() #1 /home/clubnation.com.br/public_html/wp-content/plugins/medoid/medoid.php(20): Medoid::instance() #2 /home/clubnation.com.br/public_html/wp-content/plugins/medoid/medoid.php(24): medoid() #3 /home/clubnation.com.br/public_html/wp-admin/includes/plugin.php(2299): include('/home/clubnatio...') #4 /home/clubnation.com.br/public_html/wp-admin/plugins.php(191): plugin_sandbox_scrape() #5 {main} thrown in /home/clubnation.com.br/public_html/wp-content/plugins/medoid/includes/class-medoid.php on line 22

**Comment by puleeno** [comment]
Hi @PauloBoaventura,
Sorry for the late response.

The plugin is in development. So the structure has many changes so it can make the bugs. 
To fix missing classes please use Composer to install dependences packages.

# Command:
```
cd wp-content/plugins/medoid
composer install
```

Thanks for your interest. Please use the release version in the next few months
